codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
      python:
        target: auto
        threshold: 1%
        flags: 
          - python
      typescript:
        target: auto
        threshold: 1%
        flags:
          - typescript
      go:
        target: auto
        threshold: 1%
        flags:
          - go
      rust:
        target: auto
        threshold: 1%
        flags:
          - rust
          
    patch:
      default:
        target: auto
        threshold: 1%

parsers:
  javascript:
    enable_partials: yes

flags:
  python:
    paths:
      - "python/**"
  typescript:
    paths:
      - "typescript/**"
  go:
    paths:
      - "go/**"
  rust:
    paths:
      - "rust/**"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
