name: Build and publish Typescript SDK
on:
  workflow_call:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release package ready to be published or not.

  workflow_dispatch:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release package ready to be published or not.

jobs:
  build-publish-typescript-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get tag version
        run: |
          echo "SDK_VERSION=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_ENV

      - name: Create nightly version, if applicable.
        if: ${{ inputs.is_release == 'false' }}
        run: |
          echo "SDK_VERSION=${{ env.SDK_VERSION }}+git$(date +'%Y%m%d').$(git rev-parse --short HEAD)-${{ github.GITHUB_RUN_ATTEMPT }}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Set the package version.
        run: |
          yarn version -i ${{ env.SDK_VERSION }}

      - name: Build
        run: |
          yarn install --immutable
          yarn build     

      - name: Share artifacts.
        uses: actions/upload-artifact@v4
        with:
          name: "realitydefender-sdk-typescript-${{ env.SDK_VERSION }}"
          path: |
            package.tgz
          compression-level: 0
          retention-days: 14
          if-no-files-found: error

      - name: Publish
        if: ${{ inputs.is_release == 'true' }}
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> .npmrc
          echo "npmAuthToken: \"${{ secrets.NODE_AUTH_TOKEN }}\"" > .yarnrc.yml
          echo "npmPublishRegistry: \"https://registry.npmjs.org/\"" >> .yarnrc.yml
          echo "npmAlwaysAuth: true" >> .yarnrc.yml
          yarn npm publish --access public
