name: Bump Version

on:
  workflow_run:
    workflows: ["Test TypeScript SDK"]
    types:
      - completed
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN || '' }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup Yarn
        run: corepack enable
          
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git remote set-url origin git@github.com:${{ github.repository }}.git
      
      - name: Install dependencies
        run: yarn install
      
      - name: Bump patch version
        run: |
          yarn version patch -m "[GitHub Action] Patch Version Bump"
          git push
          git push --tags 
