name: Bump Version

on:
  workflow_run:
    workflows: ["Test TypeScript SDK"]
    types:
      - completed
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN || '' }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Bump minor version
        run: |
          npm version minor -m "[GitHub Action] Minor Version Bump"
          git push
          git push --tags 
